
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Satham.Lahari
 */
public class bildetails extends javax.swing.JFrame {

    
    Connection conn=null;
    Statement st=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    static String id;
    static String roomnumber;
    static String indate;
    static String outdate;
    static String price;
    static String days;
    /**
     * Creates new form bildetails
     */
    public bildetails() {
        initComponents();
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
             String url = "jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=CONVERT_TO_NULL";
             //"jdbc:MySQL://localhost:3306/dbms_project";//?useSSL=false
             String mysql_user="root";
             String mysqlpswrd="Lahari@123";
             conn = DriverManager.getConnection(url,mysql_user,mysqlpswrd);
            Statement stm =(Statement) conn.createStatement();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
         }
        showrecordtable();
    }
    public void showrecordtable() {
    try {
        pst = conn.prepareStatement("select * from bill where status = ?");
        pst.setString(1, "checkout");
        rs = pst.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int c = rsmd.getColumnCount();
        DefaultTableModel Dmodel = (DefaultTableModel) jTable1.getModel();
        Dmodel.setRowCount(0);
        while (rs.next()) {
            Vector column = new Vector();
            for (int i = 1; i <= c; i++) {
                column.add(rs.getString("id"));
                column.add(rs.getString("roomno"));
                column.add(rs.getString("indate"));
                column.add(rs.getString("outdate"));
                column.add(rs.getString("price"));
                column.add(rs.getString("days"));
            }
            Dmodel.addRow(column);
        }
    } catch (SQLException ex) {
        Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoutdate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "roomno", "indate", "dateout", "price", "noofdays", "status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 131, 969, 626));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\bill (1).png")); // NOI18N
        jLabel1.setText("customer bill details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("search by using outdate");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 170, 20));
        getContentPane().add(textoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 65, 150, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\cancel (1).png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1328, 0, 38, 42));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("double click on row to open bill");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 18, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\backk (1).jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        textoutdate.setText("");
        showrecordtable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try {
        pst = conn.prepareStatement("select * from bill where status = ? and outdate=?");
        pst.setString(1, "checkout");
        pst.setString(2,textoutdate.getText());
        rs = pst.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int c = rsmd.getColumnCount();
        DefaultTableModel Dmodel = (DefaultTableModel) jTable1.getModel();
        Dmodel.setRowCount(0);
        while (rs.next()) {
            Vector column = new Vector();
            for (int i = 1; i <= c; i++) {
                column.add(rs.getString("id"));
                column.add(rs.getString("roomno"));
                column.add(rs.getString("indate"));
                column.add(rs.getString("outdate"));
                column.add(rs.getString("price"));
                column.add(rs.getString("days"));
            }
            Dmodel.addRow(column);
        }
    } catch (SQLException ex) {
        Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
            id=(String) df.getValueAt(jTable1.getSelectedRow(),0);
            roomnumber=(String) df.getValueAt(jTable1.getSelectedRow(),1);
            indate=(String) df.getValueAt(jTable1.getSelectedRow(),2);
            outdate=(String) df.getValueAt(jTable1.getSelectedRow(),3);
            price=(String) df.getValueAt(jTable1.getSelectedRow(),4);
            days=(String) df.getValueAt(jTable1.getSelectedRow(),5);
           
              new billprint().setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bildetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bildetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bildetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bildetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bildetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textoutdate;
    // End of variables declaration//GEN-END:variables
}
