
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Satham.Lahari
 */
public class checkout extends javax.swing.JFrame {
    Connection conn=null;
     Statement st=null;
     PreparedStatement pst=null;
     ResultSet rs=null;
    /**
     * Creates new form checkout
     */
    public checkout() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        textdate.setText(obj.format(date));
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
             String url = "jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=CONVERT_TO_NULL";
             //"jdbc:MySQL://localhost:3306/dbms_project";//?useSSL=false
             String mysql_user="root";
             String mysqlpswrd="Lahari@123";
             conn = DriverManager.getConnection(url,mysql_user,mysqlpswrd);
            Statement stm =(Statement) conn.createStatement();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
         }
        showdataintotable();
    }
    public void showdataintotable(){
        try {
            pst=conn.prepareStatement("select * from hoteladmin where status=?");
            pst.setString(1,"checkout");
            
            rs=pst.executeQuery();
            ResultSetMetaData ob=rs.getMetaData();
            int n=ob.getColumnCount();
            DefaultTableModel Df=(DefaultTableModel) jTable1.getModel();
            Df.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<=n;i++){
                    v.add(rs.getString("noofcust"));
                    v.add(rs.getString("indate"));
                    v.add(rs.getString("custname"));
                    v.add(rs.getString("mobile"));
                    v.add(rs.getString("days"));
                    v.add(rs.getString("price"));
                    v.add(rs.getString("status"));
            
                    
                }
            Df.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textroomnumber = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textmobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textdays = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textamount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        custno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\cancel (1).png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 30, 31));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\checko (1).png")); // NOI18N
        jLabel1.setText("CUSTOMER CHECKOUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 37, 290, 61));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 108, 130, 40));
        getContentPane().add(textroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 30));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 100, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("customer name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });
        getContentPane().add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("mobile number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));
        getContentPane().add(textmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("check out date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, 27));
        getContentPane().add(textdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "noofcust", "indate", "custname", "mobilenumber", "days", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 870, 400));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("check out now");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 100, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("no of days");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        textdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdaysActionPerformed(evt);
            }
        });
        getContentPane().add(textdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 140, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("total amount");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, 20));

        textamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textamountActionPerformed(evt);
            }
        });
        getContentPane().add(textamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 140, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("roomno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 90, 20));
        getContentPane().add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 110, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("custno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 110, -1));
        getContentPane().add(custno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\backk (1).jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            pst=conn.prepareStatement("select * from hotelcustomer where email=? and status=?");
    pst.setString(1,textroomnumber.getText());
    pst.setString(2,"booked");
            rs=pst.executeQuery();
            if(rs.next()){
                textname.setText(rs.getString("name"));
                textmobile.setText(rs.getString("mobile"));
               roomno.setText(rs.getString("roomno"));
               custno.setText(rs.getString("noofcust"));


            }
            pst=conn.prepareStatement("select * from hoteladmin where status=?");
    
    pst.setString(1,"null");
    rs=pst.executeQuery();
    if(rs.next()){
            try {
    
    String s1, s2;
    s1 = textdate.getText();
    s2 = rs.getString("indate");
    
    SimpleDateFormat obj = new SimpleDateFormat("yyyy-MM-dd");
    Date d1 = obj.parse(s1);
    
    // Use the correct format for parsing rs.getString("date")
    obj.applyPattern("yyyy-MM-dd");
    Date d2 = obj.parse(s2);

    long diff = d1.getTime() - d2.getTime();
    int days = (int) (diff / (24 * 60 * 60 * 1000));
    if (days == 0) {
        days = 1;
    }
    textdays.setText(String.valueOf(days));

    double price = Double.parseDouble(rs.getString("price")) * days;
    textamount.setText(String.valueOf(price));
} catch (ParseException | SQLException ex) {
    Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
}
    }
            
                    } catch (SQLException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         textname.setText("");
         textroomnumber.setText("");
         textmobile.setText("");
         textdate.setText("");
        textamount.setText("");
        textdays.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            pst=conn.prepareCall("update hotelcustomer set status=? where email=?");
            pst.setString(1,"checkout");
            pst.setString(2,textroomnumber.getText());
            pst.executeUpdate();
             pst=conn.prepareCall("update hoteladmin set status=? where noofcust=?");
            pst.setString(1,"checkout");
            pst.setString(2,custno.getText());
            pst.executeUpdate();
            pst=conn.prepareCall("update hotelrooms set status=? where roomno=?");
            pst.setString(1,"not-booked");
            pst.setString(2,roomno.getText());
            pst.executeUpdate();
             pst=conn.prepareCall("update hoteladmin set price=? where status=?");
            pst.setString(1,textamount.getText());
           pst.setString(2,"checkout");
            pst.executeUpdate();
             pst=conn.prepareCall("update bill set outdate=? where roomno=?");
            pst.setString(1,textdate.getText());
          pst.setString(2,roomno.getText());
            pst.executeUpdate();
             pst=conn.prepareCall("update bill set status=? where roomno=?");
            pst.setString(1,"checkout");
          pst.setString(2,roomno.getText());
            pst.executeUpdate();
             pst=conn.prepareCall("update bill set price=? where roomno=?");
            pst.setString(1,textamount.getText());
          pst.setString(2,roomno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"checkout successfully");
            showdataintotable();
            textname.setText("");
         textroomnumber.setText("");
         textmobile.setText("");
         textdate.setText("");
        textamount.setText("");
        textdays.setText("");
        roomno.setText("");
        custno.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"cross check details");
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void textdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdaysActionPerformed

    private void textamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textamountActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField roomno;
    private javax.swing.JTextField textamount;
    private javax.swing.JTextField textdate;
    private javax.swing.JTextField textdays;
    private javax.swing.JTextField textmobile;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textroomnumber;
    // End of variables declaration//GEN-END:variables
}
