
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Satham.Lahari
 */
public class manageroom extends javax.swing.JFrame {

     Connection conn=null;
     Statement st=null;
     PreparedStatement pst=null;
     ResultSet rs=null;
     
    /**
     * Creates new form manageroom
     */
    public manageroom() {
        initComponents();
         try {
             Class.forName("com.mysql.cj.jdbc.Driver");
             String url = "jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=CONVERT_TO_NULL";
             //"jdbc:MySQL://localhost:3306/dbms_project";//?useSSL=false
             String mysql_user="root";
             String mysqlpswrd="Lahari@123";
             conn = DriverManager.getConnection(url,mysql_user,mysqlpswrd);
            Statement stm =(Statement) conn.createStatement();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
         }
        showrecordtable();
    }
    public void showrecordtable(){
         int c=0;
         try {
             pst=conn.prepareStatement("select * from hotelrooms");
             rs=pst.executeQuery();
             ResultSetMetaData rsmd=rs.getMetaData();
             c=rsmd.getColumnCount();
             DefaultTableModel Dmodel=(DefaultTableModel) jTable1.getModel();
             Dmodel.setRowCount(0);
             while(rs.next()){
                 Vector column=new Vector();
                 for(int i=1;i<=c;i++)
                 {
                     column.add(rs.getString("roomno"));
                     column.add(rs.getString("roomtype"));
                     column.add(rs.getString("bedtype"));
                     column.add(rs.getString("price"));
                     column.add(rs.getString("status"));
                 }
                 Dmodel.addRow(column);
             }
         } catch (SQLException ex) {
             Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textroomnumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboroomtype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textprice = new javax.swing.JTextField();
        jCombobed = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\manageroom (1).jpg")); // NOI18N
        jLabel1.setText("MANAGE ROOM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 47, 245, 69));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room number", "Room type", "Bed type", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 134, 776, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\cancel (1).png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1333, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ROOM NUMBER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 158, 42));
        getContentPane().add(textroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 230, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ROOM TYPE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 182, 42));

        jComboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));
        getContentPane().add(jComboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 190, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("BED");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, 160, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("PRICE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 170, 30));

        textprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpriceActionPerformed(evt);
            }
        });
        getContentPane().add(textprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 190, 40));

        jCombobed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE", "DOUBLE", " " }));
        jCombobed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombobedActionPerformed(evt);
            }
        });
        getContentPane().add(jCombobed, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 710, 230, 40));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("ADD ROOM DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Satham.Lahari\\Downloads\\dbmspro\\backk (1).jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(textroomnumber.getText().equals("")){
            JOptionPane.showMessageDialog(this,"all feilds should be filled");
            textroomnumber.requestFocus();
        }
        else if(textprice.getText().equals("")){
            JOptionPane.showMessageDialog(this,"all feilds should be filled");
            textprice.requestFocus();
        }
        else{
            try {
                pst=conn.prepareCall("select * from hotelrooms where roomno=?");
                pst.setString(1,textroomnumber.getText());
                rs=pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"room number already exists");
                }
                else{
                    pst=conn.prepareStatement("insert into hotelrooms(roomno,roomtype,bedtype,price,status)values(?,?,?,?,?)");
                    pst.setString(1,textroomnumber.getText());
                    pst.setString(2,jComboroomtype.getItemAt(jComboroomtype.getSelectedIndex()));
                    pst.setString(3,jCombobed.getItemAt(jCombobed.getSelectedIndex()));
                    pst.setString(4,textprice.getText());
                    pst.setString(5,"Not-booked");
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"room added");
                    showrecordtable();
                    textroomnumber.setText("");
                    textprice.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCombobedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombobedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombobedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCombobed;
    private javax.swing.JComboBox<String> jComboroomtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textprice;
    private javax.swing.JTextField textroomnumber;
    // End of variables declaration//GEN-END:variables
}
